openapi: 3.0.4
info:
  title: Profanity Filter
  description: Profanity Filter is a simple tool for filtering out profanity words from a text. It returns the text with the profanity words replaced by placeholders.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/profanityfilter:
    post:
      summary: Filter Profanity
      description: Profanity Filter is a simple tool for filtering out profanity words from a text. It returns the text with the profanity words replaced by placeholders.
      operationId: profanityfilter
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  isProfane: true
                  filteredText: Today is so **** hot! Why the **** would anyone go outside?
                  mask: '*'
                  trimmed: false
                  profaneWords: 2
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to filter profanity words from
                  example: Today is so damn hot! Why the hell would anyone go outside?
                mask:
                  type: string
                  description: The mask to replace the profanity words with. Should be a Single Character (e.g., *)
                  default: '*'
                  example: '*'
              required:
              - text
              example:
                text: Today is so damn hot! Why the hell would anyone go outside?
                mask: '*'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
